### ISSUE TITLE
Weird Screen

### ISSUE THREAD

**Issue by Erik262** [Desuuuu/DGUS-reloaded#10]
Hi folks,

does someone know what's the problem here is??
![IMG_3880](https://user-images.githubusercontent.com/11977647/106268507-84704c80-622b-11eb-8b4c-5da7ac3c7dc6.jpg)

**Comment by Desuuuu** [comment]
What's the model of your touchscreen? If you can't tell, a picture of the back of the screen would be enough as well.

**Comment by Erik262** [comment]
Of course...
![IMG_3883](https://user-images.githubusercontent.com/11977647/106306669-a931e780-625e-11eb-8a40-575ea001bc36.jpg)

**Comment by Desuuuu** [comment]
Your touchscreen isn't compatible with this firmware.

It's a 320*480 screen while this firmware is for 480*272 touchscreens (it wouldn't even work in landscape due to the different resolution).

**Comment by Erik262** [comment]
So how can I solve this? Do I have to write a completely new firmware or can I use yours and modify this a bit?

**Comment by Desuuuu** [comment]
Unless you want to rewrite the whole thing, there's no way for you to make this work with your screen.
