### ISSUE TITLE
Do I install the 2 bin files

### ISSUE THREAD

**Issue by megatech1966** [Desuuuu/DGUS-reloaded#2]
I have a stock cr10s pro v2 with a stock screen. Do I copy those 2 bin files for screen?

**Comment by Desuuuu** [comment]
If you want to use the custom G-code entry screen, you will first need to follow these steps: [Flashing the touchscreen GUI and OS firmware](https://github.com/Desuuuu/DGUS-reloaded/wiki/Flashing-the-touchscreen-GUI-and-OS-firmware).

To install the firmware itself, you can follow these: [Flashing the firmware](https://github.com/Desuuuu/DGUS-reloaded/wiki/Flashing-the-firmware).
