### ISSUE TITLE
No space symbol on gcode screen

### ISSUE THREAD

**Issue by scynthero** [Desuuuu/DGUS-reloaded#6]
I can't enter space on gcode screen, so it's mostly not usable.

**Comment by Desuuuu** [comment]
Please read [this comment](https://github.com/Desuuuu/DGUS-reloaded/issues/4#issuecomment-691053694) for an explanation about this.

I will probably update the keyboard layout soon, but in the meantime it **is** mostly usable.

**Comment by scynthero** [comment]
Oh! i didn't know that. Thanks then for such awesome feature!
